language: node_js

sudo: true

node_js:
  - "4.6.0"

cache:
  directories:
    - InstagbugDemo

before_install:
  - npm install -g react-native-cli
  #- rm -rf InstagbugDemo

notifications:
  email: false

script:
  - react-native init InstagbugDemo
  - cd InstagbugDemo
  - npm install react-native-instabug --save
  # - react-native link

after_script:
  - npm uninstall react-native-instabug --save
