language: node_js

sudo: true

node_js:
  - "4.6.0"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g react-native-cli
  - react-native init InstagbugDemo

notifications:
  email: false

script:
  - cd InstagbugDemo
  - npm install react-native-instabug --save
  - react-native link

after_script:
  - npm uninstall react-native-instabug --save
